[project]
name = "danielhoherd.github.io"
authors = [{name = "Daniel Hoherd", email = "daniel.hoherd@gmail.com"}]
version = "0.2.0"
description = "Personal website of Daniel Hoherd."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "lektor>=3.3.12",
]
